display_name: Mangayomi

icon: assets/app_icons/icon-red.png

keywords:
  - Manga
  - Anime
  - BitTorrent

generic_name: Free and open source application that allows users to read manga and stream anime from a variety of sources including BitTorrent.

categories:
  - Utility

startup_notify: true

include: []
