display_name: Mangayomi

package_name: mangayomi

maintainer:
  name: kodjodevf
  email: kodjomoustapha@gmail.com

priority: optional

section: x11

installed_size: 30600

essential: false

postinstall_scripts:
  - echo "Installed Mangayomi successfully"
  
postuninstall_scripts:
  - echo "Unistalled Mangayomi successfully"
icon: assets/app_icons/icon-red.png

keywords:
  - Manga
  - Anime
  - BitTorrent

generic_name: Free and open source application that allows users to read manga and stream anime from a variety of sources including BitTorrent.

categories:
  - Utility

startup_notify: true
